// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ViviGest.Data;

#nullable disable

namespace ViviGest.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ViviGest.Api.Models.CargoCuenta", b =>
                {
                    b.Property<Guid>("IdCargoCuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPeriodoPago")
                        .HasColumnType("int");

                    b.Property<Guid>("IdUnidad")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdCargoCuenta");

                    b.HasIndex("IdPeriodoPago");

                    b.HasIndex("IdUnidad");

                    b.ToTable("CargoCuenta");
                });

            modelBuilder.Entity("ViviGest.Api.Models.Conjunto", b =>
                {
                    b.Property<Guid>("IdConjunto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("IdConjunto");

                    b.ToTable("Conjunto", (string)null);
                });

            modelBuilder.Entity("ViviGest.Api.Models.Correspondencia", b =>
                {
                    b.Property<Guid>("IdCorrespondencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntregadoA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaEntregado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaNotificado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRecepcion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEstadoCorrespondencia")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoCorrespondencia")
                        .HasColumnType("int");

                    b.Property<Guid>("IdUnidad")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdUnidad");

                    b.Property<Guid>("IdUsuarioRegistro")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remitente")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCorrespondencia");

                    b.HasIndex("IdEstadoCorrespondencia");

                    b.HasIndex("IdTipoCorrespondencia");

                    b.HasIndex("IdUsuarioRegistro");

                    b.HasIndex("IdUnidad", "FechaRecepcion");

                    b.ToTable("Correspondencia", (string)null);
                });

            modelBuilder.Entity("ViviGest.Api.Models.EstadoCorrespondencia", b =>
                {
                    b.Property<int>("IdEstadoCorrespondencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoCorrespondencia"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdEstadoCorrespondencia");

                    b.ToTable("EstadoCorrespondencia", (string)null);
                });

            modelBuilder.Entity("ViviGest.Api.Models.MetodoPago", b =>
                {
                    b.Property<int>("IdMetodoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMetodoPago"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMetodoPago");

                    b.ToTable("MetodoPago");
                });

            modelBuilder.Entity("ViviGest.Api.Models.Pago", b =>
                {
                    b.Property<Guid>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdMetodoPago")
                        .HasColumnType("int");

                    b.Property<int>("IdPeriodoPago")
                        .HasColumnType("int");

                    b.Property<Guid>("IdUnidad")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuarioRegistro")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdPago");

                    b.HasIndex("IdMetodoPago");

                    b.HasIndex("IdPeriodoPago");

                    b.HasIndex("IdUnidad");

                    b.HasIndex("IdUsuarioRegistro");

                    b.ToTable("Pago");
                });

            modelBuilder.Entity("ViviGest.Api.Models.PeriodoPago", b =>
                {
                    b.Property<int>("IdPeriodoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPeriodoPago"));

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPeriodoPago");

                    b.ToTable("PeriodoPago");
                });

            modelBuilder.Entity("ViviGest.Api.Models.Persona", b =>
                {
                    b.Property<Guid>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdPersona");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("IdTipoDocumento")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPersona");

                    b.HasIndex("CorreoElectronico")
                        .IsUnique()
                        .HasFilter("[CorreoElectronico] IS NOT NULL");

                    b.ToTable("Persona", (string)null);
                });

            modelBuilder.Entity("ViviGest.Api.Models.PersonaAutorizada", b =>
                {
                    b.Property<Guid>("IdPersonaAutorizada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdPersona")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdTipoRelacionAutorizado")
                        .HasColumnType("int");

                    b.Property<Guid>("IdUsuarioResidente")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlacaVehiculo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPersonaAutorizada");

                    b.HasIndex("IdPersona");

                    b.HasIndex("IdTipoRelacionAutorizado");

                    b.HasIndex("IdUsuarioResidente", "IdPersona")
                        .IsUnique();

                    b.ToTable("PersonaAutorizada", (string)null);
                });

            modelBuilder.Entity("ViviGest.Api.Models.Residencia", b =>
                {
                    b.Property<Guid>("IdResidencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdUnidad")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdResidencia");

                    b.HasIndex("IdUnidad");

                    b.HasIndex("IdUsuario", "IdUnidad", "FechaInicio")
                        .IsUnique();

                    b.ToTable("Residencia", (string)null);
                });

            modelBuilder.Entity("ViviGest.Api.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdRol");

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("ViviGest.Api.Models.TipoCorrespondencia", b =>
                {
                    b.Property<int>("IdTipoCorrespondencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoCorrespondencia"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdTipoCorrespondencia");

                    b.ToTable("TipoCorrespondencia", (string)null);
                });

            modelBuilder.Entity("ViviGest.Api.Models.TipoRelacionAutorizado", b =>
                {
                    b.Property<int>("IdTipoRelacionAutorizado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoRelacionAutorizado"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdTipoRelacionAutorizado");

                    b.ToTable("TipoRelacionAutorizado", (string)null);
                });

            modelBuilder.Entity("ViviGest.Api.Models.Torre", b =>
                {
                    b.Property<Guid>("IdTorre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdConjunto")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdTorre");

                    b.HasIndex("IdConjunto", "Nombre")
                        .IsUnique();

                    b.ToTable("Torre", (string)null);
                });

            modelBuilder.Entity("ViviGest.Api.Models.Unidad", b =>
                {
                    b.Property<Guid>("IdUnidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AreaM2")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("IdTorre")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdUnidad");

                    b.HasIndex("IdTorre");

                    b.ToTable("Unidad", (string)null);
                });

            modelBuilder.Entity("ViviGest.Api.Models.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<byte[]>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("varbinary(256)");

                    b.Property<byte[]>("ContrasenaSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(128)");

                    b.Property<Guid>("IdPersona")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdPersona")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("ViviGest.Api.Models.UsuarioRol", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario", "IdRol");

                    b.HasIndex("IdRol");

                    b.ToTable("UsuarioRol", (string)null);
                });

            modelBuilder.Entity("ViviGest.Api.Models.Visita", b =>
                {
                    b.Property<Guid>("IdVisita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdUnidad")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuarioRegistro")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdVisitante")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NotaDestino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlacaVehiculo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdVisita");

                    b.HasIndex("IdUsuarioRegistro");

                    b.HasIndex("IdVisitante");

                    b.HasIndex("IdUnidad", "FechaRegistro");

                    b.ToTable("Visita", (string)null);
                });

            modelBuilder.Entity("ViviGest.Api.Models.Visitante", b =>
                {
                    b.Property<Guid>("IdVisitante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdPersona")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdVisitante");

                    b.HasIndex("IdPersona")
                        .IsUnique();

                    b.ToTable("Visitante", (string)null);
                });

            modelBuilder.Entity("ViviGest.Api.Models.CargoCuenta", b =>
                {
                    b.HasOne("ViviGest.Api.Models.PeriodoPago", "PeriodoPago")
                        .WithMany()
                        .HasForeignKey("IdPeriodoPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViviGest.Api.Models.Unidad", "Unidad")
                        .WithMany()
                        .HasForeignKey("IdUnidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PeriodoPago");

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("ViviGest.Api.Models.Correspondencia", b =>
                {
                    b.HasOne("ViviGest.Api.Models.EstadoCorrespondencia", "EstadoCorrespondencia")
                        .WithMany()
                        .HasForeignKey("IdEstadoCorrespondencia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViviGest.Api.Models.TipoCorrespondencia", "TipoCorrespondencia")
                        .WithMany()
                        .HasForeignKey("IdTipoCorrespondencia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViviGest.Api.Models.Unidad", "Unidad")
                        .WithMany("Correspondencias")
                        .HasForeignKey("IdUnidad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ViviGest.Api.Models.Usuario", "UsuarioRegistro")
                        .WithMany()
                        .HasForeignKey("IdUsuarioRegistro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoCorrespondencia");

                    b.Navigation("TipoCorrespondencia");

                    b.Navigation("Unidad");

                    b.Navigation("UsuarioRegistro");
                });

            modelBuilder.Entity("ViviGest.Api.Models.Pago", b =>
                {
                    b.HasOne("ViviGest.Api.Models.MetodoPago", "MetodoPago")
                        .WithMany()
                        .HasForeignKey("IdMetodoPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViviGest.Api.Models.PeriodoPago", "PeriodoPago")
                        .WithMany()
                        .HasForeignKey("IdPeriodoPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViviGest.Api.Models.Unidad", "Unidad")
                        .WithMany()
                        .HasForeignKey("IdUnidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViviGest.Api.Models.Usuario", "UsuarioRegistro")
                        .WithMany()
                        .HasForeignKey("IdUsuarioRegistro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetodoPago");

                    b.Navigation("PeriodoPago");

                    b.Navigation("Unidad");

                    b.Navigation("UsuarioRegistro");
                });

            modelBuilder.Entity("ViviGest.Api.Models.PersonaAutorizada", b =>
                {
                    b.HasOne("ViviGest.Api.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViviGest.Api.Models.TipoRelacionAutorizado", "TipoRelacion")
                        .WithMany()
                        .HasForeignKey("IdTipoRelacionAutorizado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViviGest.Api.Models.Usuario", "UsuarioResidente")
                        .WithMany()
                        .HasForeignKey("IdUsuarioResidente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("TipoRelacion");

                    b.Navigation("UsuarioResidente");
                });

            modelBuilder.Entity("ViviGest.Api.Models.Residencia", b =>
                {
                    b.HasOne("ViviGest.Api.Models.Unidad", "Unidad")
                        .WithMany("Residencias")
                        .HasForeignKey("IdUnidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViviGest.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unidad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ViviGest.Api.Models.Torre", b =>
                {
                    b.HasOne("ViviGest.Api.Models.Conjunto", "Conjunto")
                        .WithMany("Torres")
                        .HasForeignKey("IdConjunto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conjunto");
                });

            modelBuilder.Entity("ViviGest.Api.Models.Unidad", b =>
                {
                    b.HasOne("ViviGest.Api.Models.Torre", "Torre")
                        .WithMany("Unidades")
                        .HasForeignKey("IdTorre")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Torre");
                });

            modelBuilder.Entity("ViviGest.Api.Models.Usuario", b =>
                {
                    b.HasOne("ViviGest.Api.Models.Persona", "Persona")
                        .WithOne("Usuario")
                        .HasForeignKey("ViviGest.Api.Models.Usuario", "IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("ViviGest.Api.Models.UsuarioRol", b =>
                {
                    b.HasOne("ViviGest.Api.Models.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViviGest.Api.Models.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ViviGest.Api.Models.Visita", b =>
                {
                    b.HasOne("ViviGest.Api.Models.Unidad", "Unidad")
                        .WithMany("Visitas")
                        .HasForeignKey("IdUnidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViviGest.Api.Models.Usuario", "UsuarioRegistro")
                        .WithMany()
                        .HasForeignKey("IdUsuarioRegistro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViviGest.Api.Models.Visitante", "Visitante")
                        .WithMany()
                        .HasForeignKey("IdVisitante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unidad");

                    b.Navigation("UsuarioRegistro");

                    b.Navigation("Visitante");
                });

            modelBuilder.Entity("ViviGest.Api.Models.Visitante", b =>
                {
                    b.HasOne("ViviGest.Api.Models.Persona", "Persona")
                        .WithOne()
                        .HasForeignKey("ViviGest.Api.Models.Visitante", "IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("ViviGest.Api.Models.Conjunto", b =>
                {
                    b.Navigation("Torres");
                });

            modelBuilder.Entity("ViviGest.Api.Models.Persona", b =>
                {
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ViviGest.Api.Models.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("ViviGest.Api.Models.Torre", b =>
                {
                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("ViviGest.Api.Models.Unidad", b =>
                {
                    b.Navigation("Correspondencias");

                    b.Navigation("Residencias");

                    b.Navigation("Visitas");
                });

            modelBuilder.Entity("ViviGest.Api.Models.Usuario", b =>
                {
                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
